AWSTemplateFormatVersion: '2010-09-09'
Description: 's3 bucket for my CICD'

Parameters:
  Environment:
    Type: String
    Default: "test"
    AllowedValues: 
      - test
      - prod
      - staging

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-unique-bucket-name
      Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: Environment
        Value: !Ref GithubActionsTesting

  Outputs:
    BuketName:
      Description: 'Name of created S3 Bucket'
      Value: !Ref MyS3Bucket
      Export:
        Name: !Sub "${AWS::StackName}-${Environment}-bucket"


