name: Validate cloudformation on PR

on:
    pull_request:
        paths:
            - 'cloudformation/**'

permissions:
    pull-requests: write
    contents: read
    
    
jobs:
    validate-cfn:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: 'eu-west-2'

          - name: Validate CloudFormation Template
            run: |
              aws cloudformation validate-template --template-body file://cloudformation/S3-bucket.yaml

          - name:  Deploy stack
            run: |
              stack_name="pr-test-stack-${{github.event.pull_request.number}}"
              aws cloudformation create stack --stackname $stack_name --template-file file://cloudformation/S3-bucket.yaml --parameters ParameterKey=Environment, ParameterValue=Test

          - name: Comment on the PR
            uses: actions/github-script@v6
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                 github.issues.createComment({

                  issue_number: contex.oissue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "PR has been validated and deployed to AWS: pr-test-stack-${{github.event.pull_request.number}}"

                 })

    cleanup-on-merge:
      runs-on: ubuntu-latest
      if: github.event.pull_request.merged == true 
      steps:
        - name: configure AWS crednetials
          uses: aws-actions/configure-aws-credentials@v1
          with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: 'eu-west-2'

        - name: delete stack
          run: |
            stack_name="pr-test-stack-${{github.event.pull_request.number}}"
            aws cloudformation delete-stack --stack-name $stack_name



