
name: deploy AWS lambda  

on:  #branch 
  push:
    branches:
       - main
   

jobs:
  deploy-lambda: #name of job 
    runs-on: macos-latest # specify runner
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Set Up Python #set up python envi
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'  # Added caching for better performance

    - name: install dependencies #install packages 
      run: |
       python -m pip install --upgrade pip
       pip install -r lambdacicd/requirements.txt -t lambda/


    - name: configure AWS Credentials #set up crednetials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-2'

    - name: Deploy Lambda function #zip lambda directory 
      run: |
        cd lambda
        zip -r lambdacicd.zip . -i .
        aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambdacicd.zip

        















